### ISSUE TITLE
Client-side input validation with Formik

### ISSUE THREAD

**Issue by gaswirth** [roundhousedesigns/gtw-frontend#16]
Fields requiring validation before submission:

- email address should be properly formed
- website URL should be a valid URL, at least roughly
- Social links should follow the prescribed formats (either a URL or a handle)

**Comment by cheesehero112** [comment]
Will work on this issue.

**Comment by gaswirth** [comment]
I'm open to removing my semi-custom <EditableText ...> components if they're too tricky with Formik. They're not what I'd hoped, regardless, so if while you're working you find that a more standard <Input> component from the Chakra library would be a simpler fit. I'm not married to the Editable.

**Comment by gaswirth** [comment]
I'm open to removing my semi-custom <EditableText ...> components if they're too tricky with Formik. They're not what I'd hoped, regardless, so if while you're working you find that a more standard <Input> component from the Chakra library would be a simpler fit. I'm not married to the Editable.

**Comment by gaswirth** [comment]
Abandoning this, benefit not enough to justify added complexity.
